### ISSUE TITLE
Simplified GETing of admin-context results

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-rest-api#21]
The API returns results that are either visible on the frontend or on the backend. But it would be nice to have a simple way to get admin-only-type results. On #8 @nerrad suggested having URLs like `/v1/admin/events`, whereas I was more thinking of making this just an added filter option (eg `v1/events?filter[admin]=1`.
Either way it would be nice, but probably not essential for an MVP

**Comment by mnelson4** [comment]
There isn't much precedent in the WP API for urls like `/v1/admin/events`, although the wp.com API does have urls like `v1/events/mine`, (which I actually added to the EE API too but am second-guessing it; I added it thinking the WP API had such a thing but it doesn't).
Troubles with having "admin" in front of the collection being retrieved (eg "events") are:
- it sorta clutters up the index, because it would at least double the number of urls for EE. If we added a filter we could instead just document it
- what happens when it comes time to POST or PUT data? Do they still use `/v1/admin/events` or do they use `/v1/events` ? For POSTing or PUTting data I understand they would need the same functionality.

So I'd rather it just be a filter that could be applied

**Comment by nerrad** [comment]
keep in mind that there are contexts where POSTING and PUTTING may be valid PUBLIC requests? (i.e. spco like behaviour?)

With that said I dig what you are saying about having an `/admin/` endpoint cluttering up the index.  I wonder if there's value in having it included in a separate section of the index?

With that said, I won't push against just having a filter.

**Comment by mnelson4** [comment]
Ended up just being a filter
