### ISSUE TITLE
Code samples for API clients

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-rest-api#30]
seth suggested creating some like the code samples seth created on http://eventespresso.com/wiki/json-api-add-on/#Code_Examples.

**Comment by nerrad** [comment]
+1 to the idea.  However I looked over the examples Seth did, I think we may want to update them (and the new ones you do for the EE4 REST api) to _not_ use `file_get_contents()` and instead use the `wp_remote_request()` family of functions for the api usage examples in php.  Many servers have remote url functionality turned off for `file_get_contents()` so it's not the best function to use in an example perhaps?

**Comment by mnelson4** [comment]
ya that's an excellent point

**Comment by sethshoultes** [comment]
Please keep in that those examples are stand-alone, non-WP examples.

**Comment by mnelson4** [comment]
also an excellent point.

**Comment by mnelson4** [comment]
hey @sethshoultes what do you think about doing these examples instead in javascript? I think that's generally more portable yet (also I think I'll put them on developer.eventespresso.com as "tutorial" posts, instead of github gists)

**Comment by sethshoultes** [comment]
Ya, that works for me.

**Comment by mnelson4** [comment]
ok here they are: http://developer.eventespresso.com/tutorial/ee4-json-rest-api-code-samples/
