### ISSUE TITLE
Create endpoints for POSTing new objects

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-rest-api#4]

**Comment by jonatshift** [comment]
I'm in desperate need for the ability to create events and add users for the event (tied to the User Integration plugin)!  I have old events and registrants I would like to import to our new EE4 website...

**Comment by mnelson4** [comment]
hi jonatshift, just to check: why do you need to create events over the rest API?
Can you please describe a little what exactly you need to do to help us plan out the feature? (Eg what other technologies you plan to use, what the user experience will be, how you hope to use the API to accomplish that, etc)
Knowing that will help us build a feature that will more likely fit your needs

**Comment by jonatshift** [comment]
It doesn't need to be in the REST API to be honest.  I'm just looking for a way to import old events and registrants from another system!  I can't seem to do this anywhere and thought it would be great if I could through the REST API.

Any help on figuring out how to do this would be greatly appreciated!

Thank you.

**Comment by mnelson4** [comment]
By "another system" do you mean another installation of EE?

If so, our importer tool sounds like what you need, but it's currently being fixed. You can try it out using the 7537 branch: https://github.com/eventespresso/event-espresso-core/tree/BUG-7537
If you want to test it, use this branch on your old EE installation and use the "Export" action on the admin event listings page. This will create a CSV file of the selected events and related data (although no registrations). Then on the new EE installation, go to Events > Import tab and upload that CSV file. The events should be imported into the new site and work fine.

If by "another system" you mean a different program or wordpress plugin, then you could still use the above-mentioned branch, but you'll need to somehow generate the CSV file yourself. If you want to continue discussing the import tool it would probably be best to continue on a new ticket on our event espresso core github issue tracker, or even continue this old issue: https://github.com/eventespresso/event-espresso-core/issues/74

**Comment by jonatshift** [comment]
Hi,

Yes it's from a different event management system (Joomla's DT Register extension).  We can generate a CSV in any format with all the info EE needs.

I've been working with your support team and they suggested reverting to EE3 (http://eventespresso.com/topic/ee4-import-events-and-attendees/) which has the old import tool.  We went ahead and did that but when we import it doesn't link the user and event!  i.e. when we use the [ESPRESSO_MY_EVENTS] shortcode for the user with the same email.

Is it even possible in EE3/EE4 to import attendees, users and events and have them all related?

Thank you in advance!

**Comment by mnelson4** [comment]
currently no the EE4 importer in the above-mentioned branch doesn't import registrations either. I'd continue discussing with support, or open a new ticket in EE core, as this ticket is intended for a much different purpose.

**Comment by jonatshift** [comment]
No problem.  Thank you anyway.

**Comment by mnelson4** [comment]
We created a card on our trello public roadmap for this: https://trello.com/c/8tMyx5SA/95-add-payment-functionality-to-the-json-api
Please upvote this feature there to help prioritize it

**Comment by mnelson4** [comment]
received feedback on our survey basically upvoting this on October 25th 2015
